name: CI-production

on: 
  push:
    branches:
      - master

jobs:
      
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: amondnet/now-deployment@v2.0.3
      with:
        zeit-token: ${{ secrets.ZEIT_TOKEN }} 
        github-token: ${{ secrets.GITHUB_TOKEN }}
        now-args: '-A now.production.json --prod'