name: CI-production

on: 
  push:
    branches:
      - master

jobs:
      
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: amondnet/now-deployment@v2.0.3
      with:
        github-token: e5549130900384e19d784a275c1ba135088c98a5
        zeit-token: z15wK1OmJQMqsAlDKiF5uC0r
        now-args: '-A now.production.json --prod'